export const TRIP_INFO = {
    REQUEST: 'TRIP_INFO_REQUEST',
    ERROR: 'TRIP_INFO_ERROR',
    SUCCESS: 'TRIP_INFO_SUCCESS',
    UPDATE: 'TRIP_INFO_UPDATE',
    UNMOUNT: 'TRIP_INFO_UNMOUNT'
};
